
=== Master Realm Access Control

The `master` realm in {project_name} is a special realm. Users in the {project_name} `master` realm can get permission to manage multiple realms on the {project_name} server. When a realm is created, {project_name} automatically creates roles that grant specific permissions to access the new realm. Access to the Admin Console and Admin REST endpoints are controlled by mapping the roles to users in the `master` realm.

It is possible to create multiple super users, as well as users that can manage specific realms only.

==== Global Roles

There are two realm-level roles in the `master` realm.
These are:

* admin
* create-realm        

Users with the `admin` role are super users and have access to manage any realm on the server. Users with the `create-realm` role can create new realms. The user is granted full access to any new realm they create.

==== Realm Specific Roles

It is possible to grant management privileges, for multiple realms in the system, to admin users within the `master` realm.
Each realm in {project_name} is represented by a client in the `master` realm. The format of the name of the client is `<realm name>-realm`. These clients have client-level roles which define various level of access for managing an individual realm.

The roles available are: 

* view-realm
* view-users
* view-clients
* view-events
* manage-realm
* manage-users
* create-client
* manage-clients
* manage-events            
* view-identity-providers
* manage-identity-providers
* impersonation

Users with these roles will be able to use that specific part of the administration console only.

[NOTE]
====
Admins with the `manage-users` role can assign admin roles to users that only they themselves have. For example, if an admin has the `manage-users` role but does not have the `manage-realm` role, they will be unable to assign the `manage-realm` role to other users.
====
